#!/usr/bin/env python2

from json import load as load_json

MAX_FILES = 3
P4PKTGEN_OUTFILE = 'test-cases.json'

def generate_commands(p4pktgen_outfile, max_files):
    '''
    Generates up to `max_files` commands.txt based on the test cases generated by
    p4pktgen (`p4pktgen_outfile`)
    '''
    cmd_files = []
    with open(p4pktgen_outfile) as p4pktgen_out:
        test_cases = load_json(p4pktgen_out)
        count = 0
        for test_case in test_cases:
            count += 1
            if count > max_files: break

            result = test_case["result"]
            cmd_file = 'commands{}-{}.txt'.format(count, result)
            with open(cmd_file, 'w') as f:
                for cmd in test_case["ss_cli_setup_cmds"]:
                    f.write('{}\n'.format(cmd))
                f.close()
                cmd_files.append(cmd_file)
        p4pktgen_out.close()
    return cmd_files

def run():
    cmd_files = generate_commands(P4PKTGEN_OUTFILE, MAX_FILES)

run()
